### ISSUE TITLE
Send message to Google Home speakers when someone is press te bell

### ISSUE THREAD

**Issue by m-Aiden** [guino/BazzDoorbell#16]
Maybe someone has already found it. 
Is there a way to send a message to Google Home Speakers from the bell via bash or something?

**Comment by jilleb** [comment]
I've used Homey to get this working.
You can either call a webhook that triggers a Google TTS event on Homey or link a flow to the 433Mhz signal.

**Comment by m-Aiden** [comment]
> I've used Homey to get this working.
> You can either call a webhook that triggers a Google TTS event on Homey or link a flow to the 433Mhz signal.

Found that busybox has no curl or wget? Is there a way to send an http request?

**Comment by guino** [comment]
@m-Aiden see:
https://github.com/guino/BazzDoorbell/issues/2#issuecomment-757497746

**Comment by m-Aiden** [comment]
Already fix this.. Doorbell send a mqtt message to Home Assistant and they play a sound on Google Home.
