### ISSUE TITLE
Unable to retrieve the stream Doorbell LSC Smart Connect FW 2.9.6

### ISSUE THREAD

**Issue by McFlyPartages** [guino/BazzDoorbell#64]
Hello,

It's been two days that I can't get the flow of my doorbell despite reading the different issues and associated links.
I followed the general post [#2](https://github.com/guino/BazzDoorbell/issues/2) then more particularly the version [#13](https://github.com/guino/BazzDoorbell/issues/13)(only this last way works).

I uncommented the three lines (ONVIF, Record, Motion)

But I can't access the feed.
Whether it is in RTSP or ONVIF, via VLC, Home Assistant or HTTP.

I don't get it.

I tried with the default `user` and `password` (admin admin) and those entered in `httpd.conf` or `passwd`.

RTSP://user:passwd@192.168.10.249:8080 /8554/ 8000
http://user:password@IP:8080/cgi-bin/mjpeg.cgi

http://admin:056565099@192.168.10.249/devices/deviceinfo donne :

Is it necessary to have a ppsapp hack?

I would like to integrate it with Home Assistant via RTSP or ONVIF but also enable MQTT.

Thank you in advance if you know where it blocks.

Here is the information on the LSC Smart Connect doorbell
```
devname "Smart Home Camera
model "Bell 8S
serialno "060759555"
softwareversion "2.9.6
hardwareversion "BE8S_H1_V10_433"
firmwareversion "ppstrong-c51-tuya2_lcs-2.9.6.20200628"
authkey "HBQXNm256JOOQajt8OpCcETwLdJ2fEON"
deviceid "pp014b037f1aca36fb2d"
identity "MR2007120100112153"
pid "aaa"
WiFi MAC "d4:d2:d6:b1:e4:5c"
```

proc/cmdline
```
mem=37M console=ttyAMA0,115200n8 mtdparts=hi_sfc:192k(bld)ro,64k(env)ro,64k(enc)ro,64k(sysflg)ro,3136k(sys),4352k(app),320k(cfg) ppsAppParts=5 ppsWatchInitEnd - ip=${T//_/$'\x20'}: ::::;T=\"sleep_5;mkdir_-p_/mnt/mmc01;mount_-t_vfat_/dev/mmcblk0p1_/mnt/mmc01;/mnt/mmc01/initrun. sh&\";eval mtdparts=hi_sfc:192k(bld)ro,64k(env)ro,64k(enc)ro,64k(sysflg)ro,3136k(sys),4352k(app),320k(cfg) ppsAppParts=5 ppsWatchInitEnd
```

proc/self/root/mnt/mmc01/hack
```
done
```

Here are the contents of my MicroSD card.
```
anthony@McFly-PC-Bureau:/media/anthony/DC0B-D0A6$ ls -l
total 1272
drwxr-xr-x 2 anthony anthony 8192 1 Jan 1980 bin
-rw-r--r-- 1 anthony anthony 1152216 Dec 14 13:45 busybox
drwxr-xr-x 2 anthony anthony 8192 Jul 15 22:30 cgi-bin
-rw-r--r-- 1 anthony anthony 607 Dec 14 13:50 custom.sh
-rw-r--r-- 1 anthony anthony 131 Jul 15 22:30 dropbearmulti
-rw-r--r-- 1 anthony anthony 314 Dec 14 13:40 env
-rw-r--r-- 1 anthony anthony 5 1 Jan. 1980 hack
drwxr-xr-x 8 anthony anthony 8192 1 Jan 1980 home
-rw-r--r-- 1 anthony anthony 23 Dec 14 13:48 httpd.conf
-rw-r--r-- 1 anthony anthony 1327 15 Jul. 22:30 index.html
-rw-r--r-- 1 anthony anthony 425 10 Jan. 2021 initrun.sh
-rw-r--r-- 1 anthony anthony 7956 Jul 15 22:30 jpeg-arm
drwxr-xr-x 2 anthony anthony 8192 1 Jan. 1980 lib
-rw-r--r-- 1 anthony anthony 39 Dec 14 13:48 passwd
-rw-r--r-- 1 anthony anthony 102 Dec 22, 2020 ppsMmcTool.txt
drwxr-xr-x 3 anthony anthony 8192 Dec 14 13:09 SDT
-rw-r--r-- 1 anthony anthony 263 15 Jul. 22:30 set
-rw-r--r-- 1 anthony anthony 1038 Dec 14:10 tuya_config.json
-rw-r--r-- 1 anthony anthony 161 Jul 15 22:30 upload.html

```

I added a `user` and a `password` in `httpd.conf` and in HASH DES version in `passwd`.

Translated with www.DeepL.com/Translator (free version)

**Comment by guino** [comment]
@McFlyPartages your device is rooted (hack is applied) based on your SD card listing.

To have RTSP enabled you'll need to patch ppsapp: just look for `ppstrong-c51-tuya2_lcs-2.9.6.20200628` in https://github.com/guino/ppsapp-rtsp/issues/1 then download the zip file and follow the how-to guide link in front of it.

For mjpeg/snap to work you'll need to edit the address (posted with the patch above) in cgi-bin/mjpeg.cgi and cgi-bin/snap.cgi in the SD card.

For home assistant integration you should follow this information (after the above is working): https://github.com/guino/BazzDoorbell/wiki/How-do-I-integrate-with-Home-Assistant,-HomeBridge,-Domoticz,-etc

**Comment by McFlyPartages** [comment]
Thank you very much, my English is not very good and so I miss some details.

I manage to have the stream and the button in MQTT but not the motion detection I will post after the topic on the Home Assistant integration.

Thanks again for the clear and quick help, but especially the work done to hack these devices.

**Comment by McFlyPartages** [comment]
Just one last question.

What is the `play.cgi` file for?
The address, should we enter it here `REQADDR=$((0x0477404))` or there `["$PLAYING" == "00000000" ]` or in both?

Thanks again.

**Comment by guino** [comment]
@McFlyPartages play.cgi is described [here](https://github.com/guino/BazzDoorbell/wiki/%5BHow-to%5D-Play-custom-sounds-trough-your-bell-speaker.) -- it allows playing audio files thru the device. You only set the address in the `REQADDR` line.

Glad you got most of it working.

**Comment by McFlyPartages** [comment]
Thanks thanks thanks
