### ISSUE TITLE
Safe to update to latest firmware after patching Action Doorbell Camera ?

### ISSUE THREAD

**Issue by Nigel1992** [guino/BazzDoorbell#66]
I want to update to the latest version but want to ensure the hack still works.

**Comment by Nigel1992** [comment]
Duplicate of #46
Sorry for misreading

**Comment by guino** [comment]
@Nigel1992 it depends on what is the latest version for your device - the hack will likely remain installed but you will need to patch the new ppsapp.

**Comment by Nigel1992** [comment]
@guino the app says 10.2.5 just like his

**Comment by guino** [comment]
@Nigel1992 for 2.10.5, yes that should work as posted in #46
