### ISSUE TITLE
DoorBell model with rj45 and RFID

### ISSUE THREAD

**Issue by WMP** [guino/BazzDoorbell#79]
Anyone trying to hack this doorbell? https://pl.aliexpress.com/item/1005003235821466.html I dont buy this now, first i looking if anyone know this model.

**Comment by WMP** [comment]
This is manufacture page: http://www.konxtech.com/Product/detail/l/en/id/5.html

**Comment by guino** [comment]
@WMP I haven't seen that device before. There's no way to know if it can be rooted from the provided pages. If you want to use RTSP/ONVIF I would recommend just buying a product that can do it out of the box. If you want something that can be rooted (for something other than RTSP/ONVIF) I would try to find product that's known to work with one of the existing hacks (that that can be hard as the same product model sometimes has different firmware). Above all I always recommend buying the product that has all the features you need OR that you can test and return for a full refund if you're not pleased with it (or it doesn't suit your needs).

Regarding the specific product you posted: 1-It doesn't use batteries (good sign it may be running linux) and 2-It is a Tuya product (good sign it may allow rooting) -- the only way to find out if we can do any mods if someone had the device to check, again, I would not suggest getting it unless it has all the features you need OR you can return if for a full refund.

**Comment by WMP** [comment]
Yes, i decided to buy https://www.dahuasecurity.com/products/productDetail/43037
